[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sanescansrv"
version = "2.1.0"
authors = [
  { name="CoolCat467" },
]
description = "Mypy extension for Python IDLE"
readme = {file = "README.md", content-type = "text/markdown"}
license = {file = "LICENSE"}
requires-python = ">=3.7"
classifiers = [
    "Development Status :: 4 - Beta",
    "Operating System :: OS Independent",
    "Typing :: Typed",
]
keywords = ["scanner", "sane", "server", "frontend"]

[project.urls]
"Homepage" = "https://github.com/CoolCat467/Scanner-Server"
"Source" = "https://github.com/CoolCat467/Scanner-Server"
"Bug Tracker" = "https://github.com/CoolCat467/Scanner-Server/issues"

[project.scripts]
sanescansrv = "sanescansrv:run"

[tool.pytest.ini_options]
addopts = "--cov-report term-missing --cov=sanescansrv"
testpaths = [
    "tests",
]

[tool.mypy]
plugins = ["trio_typing.plugin"]
mypy_path = "src"
check_untyped_defs = true
disallow_any_generics = true
disallow_untyped_calls = true
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
no_implicit_reexport = true
show_column_numbers = true
show_error_codes = true
strict = true
strict_equality = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.black]
line-length = 79
target-version = ['py311']

[tool.isort]
profile = "black"
combine_as_imports = true
line_length = 79
skip = [".git", ".github", ".venv"]

[tool.pycln]
all = true
disable_all_dunder_policy = true
